Clip animation without between-frame artifacts
GoogleChrome/ui-element-samples pull request #88
Opened 2017-05-21 19:35 UTC by ivancuric

A followup on https://twitter.com/ChromiumDev/status/845402027362521088

I added 2 raf-s to figure out the refresh rate of the device in order to accomodate varying refresh rates. It's wrapped in a `requestIdleCallback` and promisified to give the thread breathing room for accurate detection.
The animation is then defined per frame and uses `animation-timing-function: step-end` to only render the those needed.

In theory, this approach _should_ not cause mid-frame artifacts, generates ~1/10th of the frames for usual ~200-ish durations and is a bit fancier. Should be easier processing wise as well.

2017-05-21 19:40 UTC, ivancuric commented
Remade this pull request to fix the CLA errors.

2017-05-22 01:56 UTC, surma requested changes
Took a stab at this. Got a few remarks. Let me know what you think :)

2017-05-22 01:56 UTC, surma commented on animated-clip/menu.js
> +    this._getRefreshRate()
This is pretty unreliable, esp. because it get’s executed right after load where the frames are more likely to blow through the frame budget. Is this really worth the effort than assuming 60fps?

Additionally this would be a somewhat major addition since the article which could confuse readers.

2017-05-22 01:56 UTC, surma commented on animated-clip/menu.js
> +        console.log(`Refresh rate should be ${this._refreshRate}Hz`);
Please remove `console.log`s

2017-05-22 01:56 UTC, surma commented on animated-clip/menu.js
> +    console.log(`Total of ${this._nFrames} frames`);
Please remove `console.log`s

2017-05-22 01:56 UTC, surma commented on animated-clip/menu.js
> +    }
The indentation down here seems wonky

2017-05-22 01:56 UTC, surma commented on animated-clip/menu.js
> +    this._duration = window.getComputedStyle(this._menu).animationDuration
Not the biggest fan of `getComputedStyle` here. I see where you are coming from, but it might jank other animations that are running on the page. Maybe we can find a better way to get that value or leave it up to the user to use `getComputedStyle` or something else.

2017-05-22 11:27 UTC, ivancuric commented on animated-clip/menu.js
> +    this._duration = window.getComputedStyle(this._menu).animationDuration
Shouldn't be an issue, at least in this example. Small cost + work is done before events are even bound. Plus it keeps things DRY. But I guess it's better to avoid it and hard-code it.

2017-05-22 14:57 UTC, ivancuric commented on animated-clip/menu.js
> +    }
Not sure what happened there ¯\_(ツ)_/¯

2017-05-22 20:12 UTC, ivancuric commented on animated-clip/menu.js
> +    this._getRefreshRate()
Yep. Might have gone a bit overboard. Didn't want people with 144hz monitors to actually get _worse_ performance.
Wish there was an API that would report your monitor's refresh rate :)

2017-05-23 14:06 UTC, ivancuric commented
Should be truer to the original now. Interested to hear your take on it.

2017-05-29 16:41 UTC, ivancuric commented on animated-clip/menu.js
> +    }
The file looks fine now.
https://raw.githubusercontent.com/ivancuric/ui-element-samples/per-frame/animated-clip/menu.js

2017-05-29 16:44 UTC, ivancuric commented
*poke*

Any chance you'll have some spare time to review soon-ish  :)?
Beefing up my portfolio for a position, and an accepted PR from the Surminator considering web perf. would be a_muy_zing.

2017-05-29 16:48 UTC, surma commented on animated-clip/menu.js
> +    }
No, it’s still indented by 2 spaces.

2017-05-29 16:49 UTC, surma commented
All looks good except the indentation :D

2017-05-29 17:10 UTC, ivancuric commented
Derp. There we go. I'm useless without ESlint.

2017-05-29 17:39 UTC, surma commented
Nice job! 🎉 🎉 🎉 🎉

2017-05-29 17:39 UTC, merged

2017-05-29 18:00 UTC, ivancuric commented
Yäy.